version: '3.8'

services:
  wastewise-frontend:
    image: basyir/wastewise-30-frontend:latest
    container_name: wastewise-frontend
    restart: always
    ports:
      - "127.0.0.1:8899:8899"
    env_file:
      - .env
    depends_on:
      - wastewise-backend

  wastewise-backend:
    image: basyir/wastewise-30-backend:latest
    container_name: wastewise-backend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
